import { test, expect } from '@playwright/test'
import { applyAuth, loadSession, preparePage } from './helpers'

test('mestre cria, edita e confirma exclusão de arco pelo mapa', async ({ page, context }) => {
  const session = loadSession()
  await applyAuth(context, session)
  await preparePage(page, { locale: 'pt-BR', theme: 'light' })
  await page.goto(`/c/${session.slug}`)
  await page.getByTitle('Modo edição desligado — clicar para editar').click()
  await page.getByRole('button', { name: 'Menu de ferramentas do mapa' }).click()
  await page.getByRole('menuitem', { name: 'Gerenciar arcos' }).click()
  await page.getByRole('button', { name: '+ Novo arco' }).click()
  await page.locator('.ui-drawer input').nth(0).fill('Arco E2E criado')
  const createResponse = page.waitForResponse((response) =>
    response.request().method() === 'POST' && response.url().endsWith(`/api/c/${session.slug}/admin/arcos`),
  )
  await page.getByRole('button', { name: 'Salvar' }).click()
  expect((await createResponse).status()).toBe(201)
  const afterCreate = await page.request.get(`/api/c/${session.slug}/admin/arcos`)
  expect((await afterCreate.json()).some((item: { titulo: string }) => item.titulo === 'Arco E2E criado')).toBe(true)
  await page.getByRole('button', { name: 'Voltar à lista' }).click()
  await page.getByRole('button', { name: 'Menu de ferramentas do mapa' }).click()
  await page.getByRole('menuitem', { name: 'Gerenciar arcos' }).click()
  const row = page.locator('.list-row', { hasText: 'Arco E2E criado' })
  await row.getByRole('button', { name: 'Acções da linha' }).click()
  await page.getByRole('menuitem', { name: 'Editar' }).click()
  await page.locator('.ui-drawer input').nth(0).fill('Arco E2E editado')
  await page.locator('.ui-drawer input[type="number"]').fill('0')
  const updateResponse = page.waitForResponse((response) =>
    response.request().method() === 'PUT' && response.url().includes(`/api/c/${session.slug}/admin/arcos/`),
  )
  await page.getByRole('button', { name: 'Salvar' }).click()
  expect((await updateResponse).status()).toBe(200)
  const afterEdit = await page.request.get(`/api/c/${session.slug}/admin/arcos`)
  expect((await afterEdit.json()).some((item: { titulo: string }) => item.titulo === 'Arco E2E editado')).toBe(true)
  await page.getByRole('button', { name: 'Voltar à lista' }).click()
  await page.getByRole('button', { name: 'Menu de ferramentas do mapa' }).click()
  await page.getByRole('menuitem', { name: 'Gerenciar arcos' }).click()
  const edited = page.locator('.list-row', { hasText: 'Arco E2E editado' })
  await edited.getByRole('button', { name: 'Acções da linha' }).click()
  await page.getByRole('menuitem', { name: 'Excluir' }).click()
  await expect(page.getByText('Os locais serão mantidos no mapa, mas ficarão sem arco.')).toBeVisible()
  await page.getByRole('button', { name: 'Cancelar' }).click()
  await expect(page.getByText('Arco E2E editado')).toBeVisible()
  await edited.getByRole('button', { name: 'Acções da linha' }).click()
  await page.getByRole('menuitem', { name: 'Excluir' }).click()
  await page.getByRole('button', { name: 'Excluir', exact: true }).last().click()
  await expect(page.getByText('Arco E2E editado')).toHaveCount(0)
})
