import { test, expect } from '@playwright/test'
import { applyAuth, loadSession, preparePage } from './helpers'

test('mestre cria, edita e confirma exclusão de arco pelo mapa', async ({ page, context }) => {
  const session = loadSession()
  await applyAuth(context, session)
  await preparePage(page, { locale: 'pt-BR', theme: 'light' })
  await page.goto(`/c/${session.slug}`)
  await page.getByRole('button', { name: 'Menu de ferramentas do mapa' }).click()
  await page.getByRole('menuitem', { name: 'Gerenciar arcos' }).click()
  await page.getByRole('button', { name: '+ Novo arco' }).click()
  await page.locator('.ui-drawer input').nth(0).fill('Arco E2E criado')
  await page.getByRole('button', { name: 'Salvar' }).click()
  await expect(page.getByText('Arco E2E criado')).toBeVisible()
  await page.getByRole('button', { name: 'Voltar à lista' }).click()
  await page.getByRole('button', { name: 'Menu de ferramentas do mapa' }).click()
  await page.getByRole('menuitem', { name: 'Gerenciar arcos' }).click()
  const row = page.locator('.list-row', { hasText: 'Arco E2E criado' })
  await row.getByRole('button', { name: 'Editar' }).click()
  await page.locator('.ui-drawer input').nth(0).fill('Arco E2E editado')
  await page.locator('.ui-drawer input[type="number"]').fill('0')
  await page.getByRole('button', { name: 'Salvar' }).click()
  await expect(page.getByText('Arco E2E editado')).toBeVisible()
  const edited = page.locator('.list-row', { hasText: 'Arco E2E editado' })
  await edited.getByRole('button', { name: 'Excluir' }).click()
  await expect(page.getByText('Os locais serão mantidos no mapa, mas ficarão sem arco.')).toBeVisible()
  await page.getByRole('button', { name: 'Cancelar' }).click()
  await expect(page.getByText('Arco E2E editado')).toBeVisible()
  await edited.getByRole('button', { name: 'Excluir' }).click()
  await page.getByRole('button', { name: 'Excluir', exact: true }).last().click()
  await expect(page.getByText('Arco E2E editado')).toHaveCount(0)
})
