import { test, expect } from '@playwright/test'
import { applyAuth, loadSession, preparePage } from './helpers'

test('mestre move/cancela grupo, alterna formato e mantém posição após falha', async ({ page, context }) => {
  const session = loadSession()
  await applyAuth(context, session)
  await preparePage(page, { locale: 'pt-BR', theme: 'light' })
  await page.goto(`/c/${session.slug}`)
  await page.getByTitle('Modo edição desligado — clicar para editar').click()
  const group = page.locator('#map-party')
  const before = await group.getAttribute('style')
  const initialResponse = await page.request.get(`/api/c/${session.slug}/grupo`)
  const initialGroup = await initialResponse.json()

  await page.getByRole('button', { name: 'Menu de ferramentas do mapa' }).click()
  await page.getByRole('menuitem', { name: 'Mover grupo' }).click()
  await expect(page.locator('.campaign-map__banner')).toContainText('Clique no mapa para definir a nova posição do grupo.')
  await page.getByRole('button', { name: 'Cancelar' }).click()
  await expect(group).toHaveAttribute('style', before ?? '')
  expect((await (await page.request.get(`/api/c/${session.slug}/grupo`)).json()).x).toBe(initialGroup.x)

  await page.getByRole('button', { name: 'Menu de ferramentas do mapa' }).click()
  await page.getByRole('menuitem', { name: 'Mover grupo' }).click()
  await page.route(`**/api/c/${session.slug}/admin/grupo`, (route) => route.abort())
  const map = page.locator('.campaign-map__stage')
  await map.click({ position: { x: 180, y: 220 } })
  await expect(page.getByRole('alert')).toContainText('Não foi possível salvar')
  await expect(group).toHaveAttribute('style', before ?? '')
  await page.unrouteAll()
  await page.getByRole('button', { name: 'Tentar novamente' }).click()
  await expect(page.locator('.campaign-map__banner')).toHaveCount(0)
  const afterMove = await group.getAttribute('style')
  const moved = await (await page.request.get(`/api/c/${session.slug}/grupo`)).json()
  expect(moved.x).not.toBe(initialGroup.x)

  await page.getByRole('button', { name: 'Menu de ferramentas do mapa' }).click()
  await page.getByRole('menuitem', { name: 'Usar brasão' }).click()
  await expect(group).toHaveClass(/campaign-map__party--brasao/)
  await expect(group).toHaveAttribute('style', afterMove ?? '')
  const formatted = await (await page.request.get(`/api/c/${session.slug}/grupo`)).json()
  expect(formatted.formato).toBe('brasao')
  expect([formatted.x, formatted.y]).toEqual([moved.x, moved.y])
  await page.getByTitle('Modo edição ligado — clicar para ver como jogador').click()
  await expect(page.getByRole('button', { name: 'Menu de ferramentas do mapa' })).toHaveCount(0)
})
